project_id = "qqzrjaizioapwzoprvio"

[functions.complete-student-signup]
verify_jwt = true

[functions.list-prompts]
verify_jwt = false

[functions.list-ai-models]
verify_jwt = false

[functions.set-model-override]
verify_jwt = false

[functions.list-model-overrides]
verify_jwt = false

[functions.set-prompt-override]
verify_jwt = false

[functions.list-prompt-overrides]
verify_jwt = false
